language: ruby
rvm:
  - 2.6.3
os: linux
dist: xenial

install:
  - bundle install --path vendor/bundle
  - npm install

before_script:
  - chmod +x ./script/cibuild
  - python3 ./script/tag_generator.py

script: ./script/cibuild

branches:
  only:
  - master

env:
  global:
  - NOKOGIRI_USE_SYSTEM_LIBRARIES=true

addons:
  apt:
    packages:
    - libcurl4-openssl-dev

cache: bundler

notifications:
  email: false
