language: ruby
rvm:
  - 2.6.3
os: linux
dist: xenial

before_script:
  - chmod +x ./script/cibuild

script: ./script/cibuild

branches:
  only:
  - master
  - gh-pages

env:
  global:
  - NOKOGIRI_USE_SYSTEM_LIBRARIES=true

addons:
  apt:
    packages:
    - libcurl4-openssl-dev

cache: bundler

notifications:
  email: false

deploy:
  provider: pages
  skip_cleanup: true
  keep_history: true
  on:
    branch: master