title: blog of amy
email: amychurchwell@protonmail.com
description: >-
  Amy Churchwell is a software engineer in Portland, Oregon.
baseurl: ""
url: "https://amychurchwell.com"
twitter_username: amychurchwell
github_username:  amychurchwell

markdown: kramdown
hylighter: pygments

sass:
  sass_dir: _sass
  style: compact

permalink: /:categories/:title

plugins:
  - jekyll-feed

header_pages:
  - about.md

pagination:
  enabled: true
  debug: false
  collection: 'posts'
  per_page: 5
  permalink: '/:num/'
  title: ':title - page :num'
  limit: 0
  sort_reverse: true
  trail: 
    before: 2
    after: 2
  indexpage: 'index'
# Exclude from processing.
# The following items will not be processed, by default. Create a custom list
# to override the default setting.
exclude:
  - Gemfile
  - Gemfile.lock
  - node_modules
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/
