title: blog of amy
email: amychurchwell@protonmail.com
description: >-
  Amy Churchwell is a software engineer in Portland, Oregon.
baseurl: ""
url: "https://amychurchwell.com"
twitter_username: amychurchwell
github_username:  amychurchwell

markdown: kramdown
hylighter: pygments

sass:
  sass_dir: _sass
  style: compact

permalink: /:categories/:title

plugins:
  - jekyll-feed
  - jekyll-paginate

header_pages:
  - about.md

paginate: 6
paginate_path: "/blog/page:num/"

# Exclude from processing.
# The following items will not be processed, by default. Create a custom list
# to override the default setting.
exclude:
  - Gemfile
  - Gemfile.lock
  - node_modules
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/
